language: ruby
rvm:
  - 2.2.1
before_install:
  - gem update --system
  - bundle install
  - bundle update
cache: bundler
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
