# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 544eed8e5cf2bb735807e8b3d6b1259efee26738b8290a1561dd5c8e18a8e334cf7f09c786a733ff6da2c14e4b88316f3e57a81204fae20f7067322ba3cb8bd8

test:
  secret_key_base: 8afab7f8453432a0fa04f195e80368f9a063fced127f23a71017600f2be7a6ba8837ade5d4dfb41835e49de1601f70df9dfb0f82a6f3d0853e73105c43e586f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
